class fifo_driver #(parameter DATA_WIDTH = 16) extends uvm_driver #(fifo_packet);

    //fifo_packet req (gets generated by default the type is from the parameter)

    `uvm_component_utils(fifo_driver)

    function new(string name, uvm_component parent);
        super.new(name, parent);
    endfunction

    virtual interface fifo_if vif;

    int num_sent;

    task run_phase(uvm_phase phase);
        fork
            get_and_drive();
            reset_signals();
        join
    endtask

    virtual function void report_phase(uvm_phase phase);
        `uvm_info(get_type_name(), $sformatf("Report: FIFO driver sent %0d packets", num_sent), UVM_LOW)
    endfunction

    virtual function void connect_phase(uvm_phase phase);
        if(!uvm_config_db#(virtual fifo_if)::get(this, "", "vif", vif))
            `uvm_error("NOVIF", "vif not set")
    endfunction

    task get_and_drive();
        // @(negedge vif.wrst_n);
        @(posedge vif.wrst_n);
        `uvm_info(get_type_name(),"Reset Dropped", UVM_MEDIUM);
        forever begin
            wait(vif.wrst_n == 1'b1);
            seq_item_port.get_next_item(req);

            `uvm_info(get_type_name(), $sformatf("Driving Packet: \n%s", req.sprint()), UVM_HIGH)
            
            // fork
                send_to_dut(req.length, req.parity, req.write_idle_cycles, req.id, req.payload);
                // @(posedge vif.drvstart) void'(begin_tr(req, "Driver_FIFO_Packet"));
            // join

            // end_tr(req);
            
            seq_item_port.item_done();
        end
    endtask

    task reset_signals();
        forever fifo_reset();
    endtask

    task fifo_reset();
        begin
            @(negedge vif.wrst_n);
            vif.data_in <= 'hz;
            vif.w_en <= 1'b0;
            disable send_to_dut;
        end
    endtask

    task send_to_dut(
        input bit [DATA_WIDTH-1:0] length, 
        bit [DATA_WIDTH-1:0] parity, 
        int write_idle_cycles,
        bit [DATA_WIDTH-1:0] id,
        logic [DATA_WIDTH-1:0] payload[]
    );
        // $display("debug 1 %0d", length);
        repeat(write_idle_cycles) @(posedge vif.wclk);
        // $display("debug 2");
        vif.drvstart = 1'b1;
        vif.w_en <= 1'b1;

        @(negedge vif.wclk iff !vif.full);
        vif.data_in <= id;

        @(negedge vif.wclk iff !vif.full);
        vif.data_in <= length;

        for(int i=0; i<length; i++) begin
            // $display("%0t full is %0d", $time, vif.full );
            @(negedge vif.wclk iff !vif.full);
            // $display("sending payload %0d",i);
            vif.data_in <= payload[i];
            // $display("%0t full is %0d",$time, vif.full );
        end

        @(negedge vif.wclk iff !vif.full);
        vif.data_in <= parity;
        @(negedge vif.wclk iff !vif.full);

        vif.w_en <= 1'b0;
        num_sent++;
        vif.drvstart = 1'b0;
    endtask

endclass